- Target: nmaguiar/openvpn:build (alpine 3.18.4)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-45853
    PkgID: zlib@1.2.13-r1
    PkgName: zlib
    InstalledVersion: 1.2.13-r1
    FixedVersion: 1.3-r1
    Status: fixed
    Layer:
      Digest: sha256:96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa
      DiffID: sha256:cc2447e1835a40530975ab80bb1f872fbab0f2a0faecf2ab16fbbb89b3589438
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-45853
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: integer overflow and resultant heap-based buffer overflow in zipOpenNewFileInZip4_6
    Description: 'MiniZip in zlib through 1.3 has an integer overflow and resultant heap-based buffer overflow in zipOpenNewFileInZip4_64 via a long filename, comment, or extra field. NOTE: MiniZip is not a supported part of the zlib product.'
    Severity: CRITICAL
    CweIDs:
    - CWE-190
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
        V3Score: 9.8
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L
        V3Score: 5.3
    References:
    - http://www.openwall.com/lists/oss-security/2023/10/20/9
    - https://access.redhat.com/security/cve/CVE-2023-45853
    - https://chromium.googlesource.com/chromium/src/+/d709fb23806858847131027da95ef4c548813356
    - https://chromium.googlesource.com/chromium/src/+/de29dd6c7151d3cd37cb4cf0036800ddfb1d8b61
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-45853
    - https://github.com/madler/zlib/blob/ac8f12c97d1afd9bafa9c710f827d40a407d3266/contrib/README.contrib#L1-L4
    - https://github.com/madler/zlib/commit/73331a6a0481067628f065ffe87bb1d8f787d10c
    - https://github.com/madler/zlib/pull/843
    - https://nvd.nist.gov/vuln/detail/CVE-2023-45853
    - https://www.cve.org/CVERecord?id=CVE-2023-45853
    - https://www.winimage.com/zLibDll/minizip.html
    PublishedDate: '2023-10-14T02:15:00Z'
    LastModifiedDate: '2023-10-20T21:15:00Z'
