- Target: nmaguiar/openvpn:latest (alpine 3.19.1)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-22365
    PkgID: linux-pam@1.5.3-r7
    PkgName: linux-pam
    PkgIdentifier:
      PURL: pkg:apk/alpine/linux-pam@1.5.3-r7?arch=x86_64&distro=3.19.1
    InstalledVersion: 1.5.3-r7
    FixedVersion: 1.6.0-r0
    Status: fixed
    Layer:
      Digest: sha256:401045b4162dbef04e42a60638e1e8485ce52280652adc0514915a447fd4b40f
      DiffID: sha256:0aa5790c9060de07bf7684190f9a3a84d42038b0cb76f1a87807327105f73dc6
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-22365
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'pam: allowing unpriledged user to block another user namespace'
    Description: linux-pam (aka Linux PAM) before 1.6.0 allows attackers to cause a denial of service (blocked login process) via mkfifo because the openat call (for protect_dir) lacks O_DIRECTORY.
    Severity: MEDIUM
    VendorSeverity:
      amazon: 1
      nvd: 2
      photon: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.5
    References:
    - http://www.openwall.com/lists/oss-security/2024/01/18/3
    - https://access.redhat.com/security/cve/CVE-2024-22365
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-22365
    - https://github.com/linux-pam/linux-pam
    - https://github.com/linux-pam/linux-pam/commit/031bb5a5d0d950253b68138b498dc93be69a64cb
    - https://github.com/linux-pam/linux-pam/releases/tag/v1.6.0
    - https://nvd.nist.gov/vuln/detail/CVE-2024-22365
    - https://ubuntu.com/security/notices/USN-6588-1
    - https://ubuntu.com/security/notices/USN-6588-2
    - https://www.cve.org/CVERecord?id=CVE-2024-22365
    - https://www.openwall.com/lists/oss-security/2024/01/18/3
    PublishedDate: '2024-02-06T08:15:52.203Z'
    LastModifiedDate: '2024-02-14T00:27:40.143Z'
