- Target: nmaguiar/openvpn:build (alpine 3.18.2)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-3446
    PkgID: libcrypto3@3.1.1-r2
    PkgName: libcrypto3
    InstalledVersion: 3.1.1-r2
    FixedVersion: 3.1.1-r3
    Layer:
      Digest: sha256:a87caf1492b17eb5006fef5ca7c4c5ac07bc45db3580cfa3a1e26eae9a352976
      DiffID: sha256:84e71479a654277d194d7c18fbf8fc8087dd4d4e1f02819a0bfa290fa28b4d2e
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-3446
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Checking excessively long DH keys or parameters may be  ...'
    Description: Excessive time spent checking DH keys and parameters
    Severity: LOW
    References:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-3446
    - https://www.openssl.org/news/secadv/20230719.txt
  - VulnerabilityID: CVE-2023-3446
    PkgID: libssl3@3.1.1-r2
    PkgName: libssl3
    InstalledVersion: 3.1.1-r2
    FixedVersion: 3.1.1-r3
    Layer:
      Digest: sha256:a87caf1492b17eb5006fef5ca7c4c5ac07bc45db3580cfa3a1e26eae9a352976
      DiffID: sha256:84e71479a654277d194d7c18fbf8fc8087dd4d4e1f02819a0bfa290fa28b4d2e
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-3446
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Checking excessively long DH keys or parameters may be  ...'
    Description: Excessive time spent checking DH keys and parameters
    Severity: LOW
    References:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-3446
    - https://www.openssl.org/news/secadv/20230719.txt
  - VulnerabilityID: CVE-2023-3446
    PkgID: openssl@3.1.1-r2
    PkgName: openssl
    InstalledVersion: 3.1.1-r2
    FixedVersion: 3.1.1-r3
    Layer:
      Digest: sha256:a87caf1492b17eb5006fef5ca7c4c5ac07bc45db3580cfa3a1e26eae9a352976
      DiffID: sha256:84e71479a654277d194d7c18fbf8fc8087dd4d4e1f02819a0bfa290fa28b4d2e
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-3446
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Checking excessively long DH keys or parameters may be  ...'
    Description: Excessive time spent checking DH keys and parameters
    Severity: LOW
    References:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-3446
    - https://www.openssl.org/news/secadv/20230719.txt
