- Target: nmaguiar/openvpn:build (alpine 3.23.4)
  Class: os-pkgs
  Type: alpine
  Packages: []
  Vulnerabilities:
  - VulnerabilityID: CVE-2026-40200
    PkgID: musl@1.2.5-r23
    PkgName: musl
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl@1.2.5-r23?arch=x86_64&distro=3.23.4
      UID: dca30b3fd6708a32
    InstalledVersion: 1.2.5-r23
    FixedVersion: 1.2.6-r2
    Status: fixed
    Layer:
      Digest: sha256:6a0ac1617861a677b045b7ff88545213ec31c0ff08763195a70a4a5adda577bb
      DiffID: sha256:29df493baa13de438d6d2ece3a8333032e0b7b9b9d8cce4ee82194da255f61e1
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-40200
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:068ba37c296f2404987466faa3843d8c93314a6009462e06e73578a41ea7ab07
    Title: 'musl: musl libc: Arbitrary code execution and denial of service via stack-based memory corruption in qsort'
    Description: An issue was discovered in musl libc 0.7.10 through 1.2.6. Stack-based memory corruption can occur during qsort of very large arrays, due to incorrectly implemented double-word primitives. The number of elements must exceed about seven million, i.e., the 32nd Leonardo number on 32-bit platforms (or the 64th Leonardo number on 64-bit platforms, which is not practical).
    Severity: HIGH
    CweIDs:
    - CWE-670
    VendorSeverity:
      redhat: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:C/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - http://www.openwall.com/lists/oss-security/2026/04/10/13
    - https://access.redhat.com/security/cve/CVE-2026-40200
    - https://musl.libc.org/releases.html
    - https://nvd.nist.gov/vuln/detail/CVE-2026-40200
    - https://www.cve.org/CVERecord?id=CVE-2026-40200
    - https://www.openwall.com/lists/oss-security/2026/04/10/13
    PublishedDate: '2026-04-10T17:17:14.107Z'
    LastModifiedDate: '2026-04-27T19:18:46.69Z'
  - VulnerabilityID: CVE-2026-6042
    PkgID: musl@1.2.5-r23
    PkgName: musl
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl@1.2.5-r23?arch=x86_64&distro=3.23.4
      UID: dca30b3fd6708a32
    InstalledVersion: 1.2.5-r23
    FixedVersion: 1.2.6-r1
    Status: fixed
    Layer:
      Digest: sha256:6a0ac1617861a677b045b7ff88545213ec31c0ff08763195a70a4a5adda577bb
      DiffID: sha256:29df493baa13de438d6d2ece3a8333032e0b7b9b9d8cce4ee82194da255f61e1
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-6042
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:2a920cfc32a0575953afe11373cff8d29a5cff8c7a76ec11cf63d5272ea511e3
    Title: 'musl libc: GB18030 4-byte Decoder: musl libc: Denial of Service via inefficient algorithmic complexity in iconv'
    Description: A security flaw has been discovered in musl libc up to 1.2.6. Affected is the function iconv of the file src/locale/iconv.c of the component GB18030 4-byte Decoder. Performing a manipulation results in inefficient algorithmic complexity. The attack must be initiated from a local position. To fix this issue, it is recommended to deploy a patch.
    Severity: MEDIUM
    CweIDs:
    - CWE-404
    - CWE-407
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.5
    References:
    - http://www.openwall.com/lists/oss-security/2026/04/09/19
    - https://access.redhat.com/security/cve/CVE-2026-6042
    - https://nvd.nist.gov/vuln/detail/CVE-2026-6042
    - https://vuldb.com/submit/796352
    - https://vuldb.com/vuln/356620
    - https://vuldb.com/vuln/356620/cti
    - https://www.cve.org/CVERecord?id=CVE-2026-6042
    - https://www.openwall.com/lists/oss-security/2026/04/02/10
    - https://www.openwall.com/lists/oss-security/2026/04/03/2
    PublishedDate: '2026-04-10T09:16:25.45Z'
    LastModifiedDate: '2026-04-24T18:01:13.913Z'
  - VulnerabilityID: CVE-2026-40200
    PkgID: musl-utils@1.2.5-r23
    PkgName: musl-utils
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl-utils@1.2.5-r23?arch=x86_64&distro=3.23.4
      UID: ffcf7198a9776c5f
    InstalledVersion: 1.2.5-r23
    FixedVersion: 1.2.6-r2
    Status: fixed
    Layer:
      Digest: sha256:6a0ac1617861a677b045b7ff88545213ec31c0ff08763195a70a4a5adda577bb
      DiffID: sha256:29df493baa13de438d6d2ece3a8333032e0b7b9b9d8cce4ee82194da255f61e1
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-40200
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:aa20d595f4fed7d40e55e0bbfed5ed7e8daf1d052771d24f7fe0845d8b75de56
    Title: 'musl: musl libc: Arbitrary code execution and denial of service via stack-based memory corruption in qsort'
    Description: An issue was discovered in musl libc 0.7.10 through 1.2.6. Stack-based memory corruption can occur during qsort of very large arrays, due to incorrectly implemented double-word primitives. The number of elements must exceed about seven million, i.e., the 32nd Leonardo number on 32-bit platforms (or the 64th Leonardo number on 64-bit platforms, which is not practical).
    Severity: HIGH
    CweIDs:
    - CWE-670
    VendorSeverity:
      redhat: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:C/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - http://www.openwall.com/lists/oss-security/2026/04/10/13
    - https://access.redhat.com/security/cve/CVE-2026-40200
    - https://musl.libc.org/releases.html
    - https://nvd.nist.gov/vuln/detail/CVE-2026-40200
    - https://www.cve.org/CVERecord?id=CVE-2026-40200
    - https://www.openwall.com/lists/oss-security/2026/04/10/13
    PublishedDate: '2026-04-10T17:17:14.107Z'
    LastModifiedDate: '2026-04-27T19:18:46.69Z'
  - VulnerabilityID: CVE-2026-6042
    PkgID: musl-utils@1.2.5-r23
    PkgName: musl-utils
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl-utils@1.2.5-r23?arch=x86_64&distro=3.23.4
      UID: ffcf7198a9776c5f
    InstalledVersion: 1.2.5-r23
    FixedVersion: 1.2.6-r1
    Status: fixed
    Layer:
      Digest: sha256:6a0ac1617861a677b045b7ff88545213ec31c0ff08763195a70a4a5adda577bb
      DiffID: sha256:29df493baa13de438d6d2ece3a8333032e0b7b9b9d8cce4ee82194da255f61e1
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-6042
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:73a4d19cad685484d164833336b130ce4c62da0a16e5393ee41482ce630910b9
    Title: 'musl libc: GB18030 4-byte Decoder: musl libc: Denial of Service via inefficient algorithmic complexity in iconv'
    Description: A security flaw has been discovered in musl libc up to 1.2.6. Affected is the function iconv of the file src/locale/iconv.c of the component GB18030 4-byte Decoder. Performing a manipulation results in inefficient algorithmic complexity. The attack must be initiated from a local position. To fix this issue, it is recommended to deploy a patch.
    Severity: MEDIUM
    CweIDs:
    - CWE-404
    - CWE-407
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.5
    References:
    - http://www.openwall.com/lists/oss-security/2026/04/09/19
    - https://access.redhat.com/security/cve/CVE-2026-6042
    - https://nvd.nist.gov/vuln/detail/CVE-2026-6042
    - https://vuldb.com/submit/796352
    - https://vuldb.com/vuln/356620
    - https://vuldb.com/vuln/356620/cti
    - https://www.cve.org/CVERecord?id=CVE-2026-6042
    - https://www.openwall.com/lists/oss-security/2026/04/02/10
    - https://www.openwall.com/lists/oss-security/2026/04/03/2
    PublishedDate: '2026-04-10T09:16:25.45Z'
    LastModifiedDate: '2026-04-24T18:01:13.913Z'
