- Target: nmaguiar/openvpn:latest (alpine 3.24.1)
  Class: os-pkgs
  Type: alpine
  Packages: []
  Vulnerabilities:
  - VulnerabilityID: CVE-2026-84732
    PkgID: openvpn@2.7.5-r0
    PkgName: openvpn
    PkgIdentifier:
      PURL: pkg:apk/alpine/openvpn@2.7.5-r0?arch=x86_64&distro=3.24.1
      UID: 21d18f3f4bf86a5f
    InstalledVersion: 2.7.5-r0
    FixedVersion: 2.7.7-r0
    Status: fixed
    Layer:
      Digest: sha256:b682db604bf364e34fd38fad60be9c45e8c33949ca74b24b2704df47d74d56ef
      DiffID: sha256:9a9d66af8faab58c34e35dbc96a4b27231716dccd9892eebaa5d87f386b1cdf8
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-84732
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:9182824352b68616117ca5752e19754452f28d77322c402717cd75d1bc96b0a5
    Title: 'openvpn: OpenVPN: Remote Denial of Service via crafted ACK packets'
    Description: Retransmissions of ACK packet ID in OpenVPN through 2.6.22 and 2.7.6 allow remote unauthenticated attackers to cause a denial of service via crafted inputs that trigger a timeout integer overflow
    Severity: HIGH
    CweIDs:
    - CWE-190
    VendorSeverity:
      redhat: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/security/cve/CVE-2026-84732
    - https://community.openvpn.net/Security%20Announcements/CVE-2026-84732
    - https://nvd.nist.gov/vuln/detail/CVE-2026-84732
    - https://www.cve.org/CVERecord?id=CVE-2026-84732
    PublishedDate: '2026-09-07T09:17:16.84Z'
    LastModifiedDate: '2026-09-08T19:07:52.113Z'
  - VulnerabilityID: CVE-2026-84732
    PkgID: openvpn-auth-pam@2.7.5-r0
    PkgName: openvpn-auth-pam
    PkgIdentifier:
      PURL: pkg:apk/alpine/openvpn-auth-pam@2.7.5-r0?arch=x86_64&distro=3.24.1
      UID: 1dc52e27485edea5
    InstalledVersion: 2.7.5-r0
    FixedVersion: 2.7.7-r0
    Status: fixed
    Layer:
      Digest: sha256:b682db604bf364e34fd38fad60be9c45e8c33949ca74b24b2704df47d74d56ef
      DiffID: sha256:9a9d66af8faab58c34e35dbc96a4b27231716dccd9892eebaa5d87f386b1cdf8
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-84732
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:a34987f7ed8119195ea0acc5fe7d149f6ad8a4726675c476d7811c291bf310af
    Title: 'openvpn: OpenVPN: Remote Denial of Service via crafted ACK packets'
    Description: Retransmissions of ACK packet ID in OpenVPN through 2.6.22 and 2.7.6 allow remote unauthenticated attackers to cause a denial of service via crafted inputs that trigger a timeout integer overflow
    Severity: HIGH
    CweIDs:
    - CWE-190
    VendorSeverity:
      redhat: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/security/cve/CVE-2026-84732
    - https://community.openvpn.net/Security%20Announcements/CVE-2026-84732
    - https://nvd.nist.gov/vuln/detail/CVE-2026-84732
    - https://www.cve.org/CVERecord?id=CVE-2026-84732
    PublishedDate: '2026-09-07T09:17:16.84Z'
    LastModifiedDate: '2026-09-08T19:07:52.113Z'
