stdout: {}
stderr: "[vuln] Vulnerability scanning is enabled\n2025-10-20T07:03:03Z\tINFO\t[secret] Secret scanning is enabled\n2025-10-20T07:03:03Z\tINFO\t[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning\n2025-10-20T07:03:03Z\tINFO\t[secret]"
exitcode: 1
cmd: docker run --pull always --rm -v trivy-db:/root/.cache/trivy aquasec/trivy -f json  image nmaguiar/openvpn:latest
