- Target: nmaguiar/openvpn:build (alpine 3.22.0)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-4575
    PkgID: libcrypto3@3.5.0-r0
    PkgName: libcrypto3
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcrypto3@3.5.0-r0?arch=x86_64&distro=3.22.0
      UID: d683f6106b26d3a8
    InstalledVersion: 3.5.0-r0
    FixedVersion: 3.5.1-r0
    Status: fixed
    Layer:
      Digest: sha256:fe07684b16b82247c3539ed86a65ff37a76138ec25d380bd80c869a1a4c73236
      DiffID: sha256:fd2758d7a50e2b78d275ee7d1c218489f2439084449d895fa17eede6c61ab2c4
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4575
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Use of -addreject option with the openssl x509 applicat ...'
    Description: |-
      Issue summary: Use of -addreject option with the openssl x509 application adds
      a trusted use instead of a rejected use for a certificate.

      Impact summary: If a user intends to make a trusted certificate rejected for
      a particular use it will be instead marked as trusted for that use.

      A copy & paste error during minor refactoring of the code introduced this
      issue in the OpenSSL 3.5 version. If, for example, a trusted CA certificate
      should be trusted only for the purpose of authenticating TLS servers but not
      for CMS signature verification and the CMS signature verification is intended
      to be marked as rejected with the -addreject option, the resulting CA
      certificate will be trusted for CMS signature verification purpose instead.

      Only users which use the trusted certificate format who use the openssl x509
      command line application to add rejected uses are affected by this issue.
      The issues affecting only the command line application are considered to
      be Low severity.

      The FIPS modules in 3.5, 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this
      issue.

      OpenSSL 3.4, 3.3, 3.2, 3.1, 3.0, 1.1.1 and 1.0.2 are also not affected by this
      issue.
    Severity: UNKNOWN
    CweIDs:
    - CWE-295
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/22/1
    - https://github.com/openssl/openssl/commit/e96d22446e633d117e6c9904cb15b4693e956eaa
    - https://openssl-library.org/news/secadv/20250522.txt
    PublishedDate: '2025-05-22T14:16:07.63Z'
    LastModifiedDate: '2025-05-23T15:55:02.04Z'
  - VulnerabilityID: CVE-2025-4575
    PkgID: libssl3@3.5.0-r0
    PkgName: libssl3
    PkgIdentifier:
      PURL: pkg:apk/alpine/libssl3@3.5.0-r0?arch=x86_64&distro=3.22.0
      UID: cf4ea0623db38d3c
    InstalledVersion: 3.5.0-r0
    FixedVersion: 3.5.1-r0
    Status: fixed
    Layer:
      Digest: sha256:fe07684b16b82247c3539ed86a65ff37a76138ec25d380bd80c869a1a4c73236
      DiffID: sha256:fd2758d7a50e2b78d275ee7d1c218489f2439084449d895fa17eede6c61ab2c4
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4575
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Use of -addreject option with the openssl x509 applicat ...'
    Description: |-
      Issue summary: Use of -addreject option with the openssl x509 application adds
      a trusted use instead of a rejected use for a certificate.

      Impact summary: If a user intends to make a trusted certificate rejected for
      a particular use it will be instead marked as trusted for that use.

      A copy & paste error during minor refactoring of the code introduced this
      issue in the OpenSSL 3.5 version. If, for example, a trusted CA certificate
      should be trusted only for the purpose of authenticating TLS servers but not
      for CMS signature verification and the CMS signature verification is intended
      to be marked as rejected with the -addreject option, the resulting CA
      certificate will be trusted for CMS signature verification purpose instead.

      Only users which use the trusted certificate format who use the openssl x509
      command line application to add rejected uses are affected by this issue.
      The issues affecting only the command line application are considered to
      be Low severity.

      The FIPS modules in 3.5, 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this
      issue.

      OpenSSL 3.4, 3.3, 3.2, 3.1, 3.0, 1.1.1 and 1.0.2 are also not affected by this
      issue.
    Severity: UNKNOWN
    CweIDs:
    - CWE-295
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/22/1
    - https://github.com/openssl/openssl/commit/e96d22446e633d117e6c9904cb15b4693e956eaa
    - https://openssl-library.org/news/secadv/20250522.txt
    PublishedDate: '2025-05-22T14:16:07.63Z'
    LastModifiedDate: '2025-05-23T15:55:02.04Z'
  - VulnerabilityID: CVE-2025-4575
    PkgID: openssl@3.5.0-r0
    PkgName: openssl
    PkgIdentifier:
      PURL: pkg:apk/alpine/openssl@3.5.0-r0?arch=x86_64&distro=3.22.0
      UID: 83652ab4dba219b4
    InstalledVersion: 3.5.0-r0
    FixedVersion: 3.5.1-r0
    Status: fixed
    Layer:
      Digest: sha256:ffec30006f2271406f24d3e9467acdd8fd366377c3247cd541d352024a81f838
      DiffID: sha256:c0bb5b5a892e68a09cd8eb0459bf264314d0b384d52910826a8ee4bd31403714
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4575
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Use of -addreject option with the openssl x509 applicat ...'
    Description: |-
      Issue summary: Use of -addreject option with the openssl x509 application adds
      a trusted use instead of a rejected use for a certificate.

      Impact summary: If a user intends to make a trusted certificate rejected for
      a particular use it will be instead marked as trusted for that use.

      A copy & paste error during minor refactoring of the code introduced this
      issue in the OpenSSL 3.5 version. If, for example, a trusted CA certificate
      should be trusted only for the purpose of authenticating TLS servers but not
      for CMS signature verification and the CMS signature verification is intended
      to be marked as rejected with the -addreject option, the resulting CA
      certificate will be trusted for CMS signature verification purpose instead.

      Only users which use the trusted certificate format who use the openssl x509
      command line application to add rejected uses are affected by this issue.
      The issues affecting only the command line application are considered to
      be Low severity.

      The FIPS modules in 3.5, 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this
      issue.

      OpenSSL 3.4, 3.3, 3.2, 3.1, 3.0, 1.1.1 and 1.0.2 are also not affected by this
      issue.
    Severity: UNKNOWN
    CweIDs:
    - CWE-295
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/22/1
    - https://github.com/openssl/openssl/commit/e96d22446e633d117e6c9904cb15b4693e956eaa
    - https://openssl-library.org/news/secadv/20250522.txt
    PublishedDate: '2025-05-22T14:16:07.63Z'
    LastModifiedDate: '2025-05-23T15:55:02.04Z'
