- Target: nmaguiar/openvpn:latest (alpine 3.21.3)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-4575
    PkgID: libcrypto3@3.3.3-r0
    PkgName: libcrypto3
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcrypto3@3.3.3-r0?arch=x86_64&distro=3.21.3
      UID: 294b317acd0e3d86
    InstalledVersion: 3.3.3-r0
    FixedVersion: 3.5.1-r0
    Status: fixed
    Layer:
      Digest: sha256:f18232174bc91741fdf3da96d85011092101a032a93a388b79e99e69c2d5c870
      DiffID: sha256:08000c18d16dadf9553d747a58cf44023423a9ab010aab96cf263d2216b8b350
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4575
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Use of -addreject option with the openssl x509 applicat ...'
    Description: |-
      Issue summary: Use of -addreject option with the openssl x509 application adds
      a trusted use instead of a rejected use for a certificate.

      Impact summary: If a user intends to make a trusted certificate rejected for
      a particular use it will be instead marked as trusted for that use.

      A copy & paste error during minor refactoring of the code introduced this
      issue in the OpenSSL 3.5 version. If, for example, a trusted CA certificate
      should be trusted only for the purpose of authenticating TLS servers but not
      for CMS signature verification and the CMS signature verification is intended
      to be marked as rejected with the -addreject option, the resulting CA
      certificate will be trusted for CMS signature verification purpose instead.

      Only users which use the trusted certificate format who use the openssl x509
      command line application to add rejected uses are affected by this issue.
      The issues affecting only the command line application are considered to
      be Low severity.

      The FIPS modules in 3.5, 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this
      issue.

      OpenSSL 3.4, 3.3, 3.2, 3.1, 3.0, 1.1.1 and 1.0.2 are also not affected by this
      issue.
    Severity: UNKNOWN
    CweIDs:
    - CWE-295
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/22/1
    - https://github.com/openssl/openssl/commit/e96d22446e633d117e6c9904cb15b4693e956eaa
    - https://openssl-library.org/news/secadv/20250522.txt
    PublishedDate: '2025-05-22T14:16:07.63Z'
    LastModifiedDate: '2025-05-23T15:55:02.04Z'
  - VulnerabilityID: CVE-2025-4575
    PkgID: libssl3@3.3.3-r0
    PkgName: libssl3
    PkgIdentifier:
      PURL: pkg:apk/alpine/libssl3@3.3.3-r0?arch=x86_64&distro=3.21.3
      UID: 17c776a2b6f6060c
    InstalledVersion: 3.3.3-r0
    FixedVersion: 3.5.1-r0
    Status: fixed
    Layer:
      Digest: sha256:f18232174bc91741fdf3da96d85011092101a032a93a388b79e99e69c2d5c870
      DiffID: sha256:08000c18d16dadf9553d747a58cf44023423a9ab010aab96cf263d2216b8b350
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4575
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Use of -addreject option with the openssl x509 applicat ...'
    Description: |-
      Issue summary: Use of -addreject option with the openssl x509 application adds
      a trusted use instead of a rejected use for a certificate.

      Impact summary: If a user intends to make a trusted certificate rejected for
      a particular use it will be instead marked as trusted for that use.

      A copy & paste error during minor refactoring of the code introduced this
      issue in the OpenSSL 3.5 version. If, for example, a trusted CA certificate
      should be trusted only for the purpose of authenticating TLS servers but not
      for CMS signature verification and the CMS signature verification is intended
      to be marked as rejected with the -addreject option, the resulting CA
      certificate will be trusted for CMS signature verification purpose instead.

      Only users which use the trusted certificate format who use the openssl x509
      command line application to add rejected uses are affected by this issue.
      The issues affecting only the command line application are considered to
      be Low severity.

      The FIPS modules in 3.5, 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this
      issue.

      OpenSSL 3.4, 3.3, 3.2, 3.1, 3.0, 1.1.1 and 1.0.2 are also not affected by this
      issue.
    Severity: UNKNOWN
    CweIDs:
    - CWE-295
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/22/1
    - https://github.com/openssl/openssl/commit/e96d22446e633d117e6c9904cb15b4693e956eaa
    - https://openssl-library.org/news/secadv/20250522.txt
    PublishedDate: '2025-05-22T14:16:07.63Z'
    LastModifiedDate: '2025-05-23T15:55:02.04Z'
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl@1.2.5-r9
    PkgName: musl
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl@1.2.5-r9?arch=x86_64&distro=3.21.3
      UID: d304ed094a6f35fb
    InstalledVersion: 1.2.5-r9
    FixedVersion: 1.2.5-r10
    Status: fixed
    Layer:
      Digest: sha256:f18232174bc91741fdf3da96d85011092101a032a93a388b79e99e69c2d5c870
      DiffID: sha256:08000c18d16dadf9553d747a58cf44023423a9ab010aab96cf263d2216b8b350
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-26519
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write ...
    Description: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write vulnerability when an attacker can trigger iconv conversion of untrusted EUC-KR text to UTF-8.
    Severity: UNKNOWN
    CweIDs:
    - CWE-787
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/13/2
    - http://www.openwall.com/lists/oss-security/2025/02/13/3
    - http://www.openwall.com/lists/oss-security/2025/02/13/4
    - http://www.openwall.com/lists/oss-security/2025/02/13/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/6
    - https://git.musl-libc.org/cgit/musl/commit/?id=c47ad25ea3b484e10326f933e927c0bc8cded3da
    - https://git.musl-libc.org/cgit/musl/commit/?id=e5adcd97b5196e29991b524237381a0202a60659
    - https://www.openwall.com/lists/oss-security/2025/02/13/2
    PublishedDate: '2025-02-14T04:15:09.05Z'
    LastModifiedDate: '2025-02-14T17:15:23.09Z'
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl-utils@1.2.5-r9
    PkgName: musl-utils
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl-utils@1.2.5-r9?arch=x86_64&distro=3.21.3
      UID: 3e65cfca4f8bdb20
    InstalledVersion: 1.2.5-r9
    FixedVersion: 1.2.5-r10
    Status: fixed
    Layer:
      Digest: sha256:f18232174bc91741fdf3da96d85011092101a032a93a388b79e99e69c2d5c870
      DiffID: sha256:08000c18d16dadf9553d747a58cf44023423a9ab010aab96cf263d2216b8b350
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-26519
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write ...
    Description: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write vulnerability when an attacker can trigger iconv conversion of untrusted EUC-KR text to UTF-8.
    Severity: UNKNOWN
    CweIDs:
    - CWE-787
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/13/2
    - http://www.openwall.com/lists/oss-security/2025/02/13/3
    - http://www.openwall.com/lists/oss-security/2025/02/13/4
    - http://www.openwall.com/lists/oss-security/2025/02/13/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/6
    - https://git.musl-libc.org/cgit/musl/commit/?id=c47ad25ea3b484e10326f933e927c0bc8cded3da
    - https://git.musl-libc.org/cgit/musl/commit/?id=e5adcd97b5196e29991b524237381a0202a60659
    - https://www.openwall.com/lists/oss-security/2025/02/13/2
    PublishedDate: '2025-02-14T04:15:09.05Z'
    LastModifiedDate: '2025-02-14T17:15:23.09Z'
  - VulnerabilityID: CVE-2025-4575
    PkgID: openssl@3.3.3-r0
    PkgName: openssl
    PkgIdentifier:
      PURL: pkg:apk/alpine/openssl@3.3.3-r0?arch=x86_64&distro=3.21.3
      UID: 456fe492c42d784d
    InstalledVersion: 3.3.3-r0
    FixedVersion: 3.5.1-r0
    Status: fixed
    Layer:
      Digest: sha256:de1cb8a9df95cbb9fa78a37af78f2f47e75537af82efae25a734edc5ec0edc05
      DiffID: sha256:ddc3036c4ee07d0fee8f01f7f120d94287f1b220634d517a444e69883a9e1fc5
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4575
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Use of -addreject option with the openssl x509 applicat ...'
    Description: |-
      Issue summary: Use of -addreject option with the openssl x509 application adds
      a trusted use instead of a rejected use for a certificate.

      Impact summary: If a user intends to make a trusted certificate rejected for
      a particular use it will be instead marked as trusted for that use.

      A copy & paste error during minor refactoring of the code introduced this
      issue in the OpenSSL 3.5 version. If, for example, a trusted CA certificate
      should be trusted only for the purpose of authenticating TLS servers but not
      for CMS signature verification and the CMS signature verification is intended
      to be marked as rejected with the -addreject option, the resulting CA
      certificate will be trusted for CMS signature verification purpose instead.

      Only users which use the trusted certificate format who use the openssl x509
      command line application to add rejected uses are affected by this issue.
      The issues affecting only the command line application are considered to
      be Low severity.

      The FIPS modules in 3.5, 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this
      issue.

      OpenSSL 3.4, 3.3, 3.2, 3.1, 3.0, 1.1.1 and 1.0.2 are also not affected by this
      issue.
    Severity: UNKNOWN
    CweIDs:
    - CWE-295
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/22/1
    - https://github.com/openssl/openssl/commit/e96d22446e633d117e6c9904cb15b4693e956eaa
    - https://openssl-library.org/news/secadv/20250522.txt
    PublishedDate: '2025-05-22T14:16:07.63Z'
    LastModifiedDate: '2025-05-23T15:55:02.04Z'
