ojob.io/sec/genSecBadge: ''
image: nmaguiar/openvpn:latest
file: .github/sec-latest.svg
reportFile: .github/sec-latest.yaml
init: {}
msg: Producing a summary of the results...
__key: report
level: info
options: {}
__format: pm
