name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 0 * * 6'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      name: Build and push
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: nmaguiar/openvpn:build

  Scan-Images:
    runs-on    : ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name       : Scan images
    steps      :
    - uses: actions/checkout@v3
      name: Checkoout

    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    - uses: openaf/ojob-action@v4
      name: Check latest
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/openvpn:latest file=.github/sec-latest.svg reportFile=.github/sec-latest.yaml'
        dist: 't8'

    - name: Generate sec-latest.md
      uses: openaf/ojob-action@v4
      with:
        ojob: 'ojob.io/util/toMDTree'
        args: 'inputFile=.github/sec-latest.yaml file=.github/sec-latest.md'

    - uses: openaf/ojob-action@v4
      name: Check build
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/openvpn:build file=.github/sec-build.svg reportFile=.github/sec-build.yaml'
        dist: 't8'

    - name: Generate sec-build.md
      uses: openaf/ojob-action@v4
      with:
        ojob: 'ojob.io/util/toMDTree'
        args: 'inputFile=.github/sec-build.yaml file=.github/sec-build.md'

    - uses: openaf/ojob-action@v4
      name: Update badges
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: 'ojob.io/git/hub/contentIn'
        args: 'message="update\ badge" paths=.github/'
        dist: 't8'
