name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 0 * * 6'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      name: Build and push
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: nmaguiar/openvpn:build

  Scan-Images:
    runs-on    : ubuntu-latest
    permissions:
      contents: write
    name       : Scan images
    steps      :
    - uses: actions/checkout@v3
      name: Checkoout

    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    - uses: openaf/ojob-action@v3
      name: Check latest
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/openvpn:latest file=.github/sec-latest.svg'
        dist: 't8'

    - uses: openaf/ojob-action@v3
      name: Check build
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/openvpn:build file=.github/sec-build.svg'
        dist: 't8'

    - name: Update badges
      uses: openaf/ojob-action@v3
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: 'ojob.io/git/hub/contentIn'
        args: 'message="Update\ badge"'
        dist: 't8'
